# Generated by Django 5.1 on 2024-09-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('page_number', models.PositiveIntegerField()),
                ('editorial', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=50, unique=True)),
                ('authors', models.ManyToManyField(to='authors.author')),
            ],
        ),
    ]
